In [1]:
%env NUMBA_DEBUG_CACHE = 1

env: NUMBA_DEBUG_CACHE=1


In [2]:
import numba
import numpy as np

import pytensor
import pytensor.tensor as pt

In [3]:
np.__path__

['/home/ricardo/miniforge3/envs/pytensor-dev/lib/python3.12/site-packages/numpy']

In [4]:
x_test = np.random.normal(size=(5, 3))

In [5]:
x = pt.matrix("x")
y = pt.cos(x)

In [6]:
numba.__path__

['/home/ricardo/miniforge3/envs/pytensor-dev/lib/python3.12/site-packages/numba']

In [7]:
fn = pytensor.function([x], y, mode="NUMBA")
fn.trust_input = True
fn(x_test)
%timeit fn(x_test)

[cache] index saved to '/tmp/__pycache__/tmplcm0rk0p.store_core_outputs-2.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmplcm0rk0p.store_core_outputs-2.py312.1.nbc'
[cache] index saved to '/tmp/__pycache__/tmpi8ea3z9m.numba_funcified_fgraph-1.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmpi8ea3z9m.numba_funcified_fgraph-1.py312.1.nbc'
2.88 μs ± 15.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
fn = pytensor.function([x], y, mode="NUMBA_VM")
fn.trust_input = True
fn(x_test)
%timeit fn(x_test)

[cache] index saved to '/tmp/__pycache__/tmpi875ah9b.store_core_outputs-2.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmpi875ah9b.store_core_outputs-2.py312.1.nbc'
3.17 μs ± 174 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
fn = pytensor.function([x], y, mode="FAST_RUN")
fn.trust_input = True
%timeit fn(x_test)

1.57 μs ± 14.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [42]:
fn(x_test)

array([[1.96556505, 1.60668274, 4.00981307],
       [2.0365567 , 0.22833339, 0.80101769],
       [0.39226481, 1.05788007, 2.23190361],
       [1.5690841 , 1.11887841, 3.40233009],
       [0.96677572, 0.61473753, 0.59705756]])

In [9]:
import pytensor
import pytensor.tensor as pt


x = pt.matrix("x")
y = x.T

In [14]:
%%timeit -r 1 -n 1
fn = pytensor.function([x], y, mode="NUMBA")
print(fn([[1, 2, 3]]))

[cache] index saved to '/tmp/__pycache__/tmpyy0zwgp0.store_core_outputs-2.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmpyy0zwgp0.store_core_outputs-2.py312.1.nbc'
[cache] index saved to '/tmp/__pycache__/tmp538o96n8.numba_funcified_fgraph-1.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmp538o96n8.numba_funcified_fgraph-1.py312.1.nbc'
[[ 0.54030231 -0.41614684 -0.9899925 ]]
291 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [15]:
%%timeit -r 1 -n 1
fn = pytensor.function([x], y, mode="NUMBA")
print(fn([[1, 2, 3]]))

[cache] index saved to '/tmp/__pycache__/tmpb_p6f1i0.store_core_outputs-2.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmpb_p6f1i0.store_core_outputs-2.py312.1.nbc'
[cache] index saved to '/tmp/__pycache__/tmpk5403wz0.numba_funcified_fgraph-1.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmpk5403wz0.numba_funcified_fgraph-1.py312.1.nbc'
[[ 0.54030231 -0.41614684 -0.9899925 ]]
293 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [16]:
%%timeit -r 1 -n 1
fn = pytensor.function([x], y, mode="NUMBA_VM")
fn([[1, 2, 3]])

[cache] index saved to '/tmp/__pycache__/tmpxvysg5g4.store_core_outputs-2.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmpxvysg5g4.store_core_outputs-2.py312.1.nbc'
238 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [17]:
%%timeit -r 1 -n 1
fn = pytensor.function([x], y, mode="NUMBA_VM")
fn([[1, 2, 3]])

[cache] index saved to '/tmp/__pycache__/tmp6q9e9hq8.store_core_outputs-2.py312.nbi'
[cache] data saved to '/tmp/__pycache__/tmp6q9e9hq8.store_core_outputs-2.py312.1.nbc'
239 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [ ]:
fn = pytensor.function([x], y, mode="NUMBA_VM")
fn([[1, 2, 3]])

In [8]:
%%timeit -r 1 -n 1
out = pytensor.function([x], y, mode="FAST_RUN")
out([[1, 2, 3]])

16.1 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [3]:
%env NUMBA_DEBUG_CACHE = 1

env: NUMBA_DEBUG_CACHE=1


In [4]:
%env NUMBA_LLVM_PASS_TIMINGS = 1

env: NUMBA_LLVM_PASS_TIMINGS=1


In [5]:
out = pytensor.function([x], y, mode="NUMBA")
out([[1, 2, 3]])

# md = out.vm.jit_fn.get_metadata(out.vm.jit_fn.signatures[0])
# print(md['llvm_pass_timings'])

[cache] index loaded from '/home/ricardo/Documents/pytensor/pytensor/link/numba/dispatch/__pycache__/elemwise.numba_funcify_DimShuffle.locals.dimshuffle-544.py312.nbi'
[cache] index loaded from '/home/ricardo/Documents/pytensor/pytensor/link/numba/dispatch/__pycache__/elemwise.numba_funcify_DimShuffle.locals.dimshuffle_inner-512.py312.nbi'
[cache] index loaded from '/home/ricardo/Documents/pytensor/pytensor/link/numba/dispatch/__pycache__/elemwise.numba_funcify_DimShuffle.locals.transpose-472.py312.nbi'
[cache] data loaded from '/home/ricardo/Documents/pytensor/pytensor/link/numba/dispatch/__pycache__/elemwise.numba_funcify_DimShuffle.locals.transpose-472.py312.1.nbc'
[cache] index loaded from '/home/ricardo/Documents/pytensor/pytensor/link/numba/dispatch/__pycache__/elemwise.numba_funcify_DimShuffle.locals.find_shape-493.py312.nbi'
[cache] data loaded from '/home/ricardo/Documents/pytensor/pytensor/link/numba/dispatch/__pycache__/elemwise.numba_funcify_DimShuffle.locals.find_shape-493

array([[1.],
       [2.],
       [3.]])

In [6]:
f = _DIMSHUFFLE_FNS[-1]
md = f.get_metadata(f.signatures[0])
print(md["llvm_pass_timings"])

Printing pass timings for JITCodeLibrary('numba_funcify_DimShuffle.<locals>.dimshuffle')
Total time: 0.1363
== #0 Function passes on '_ZN8pytensor4link5numba8dispatch8elemwise24numba_funcify_DimShuffle12_3clocals_3e10dimshuffleB2v2B110c8tJTIeFIjxB2IKSgI4CrvQClYb5wBbdC9Xqyfl5JUWJySXqOgrqRcBUU5yfDGLmFVeBqMS0PDBVlFygXqsJDGq0WIeaj5lGYBJFECdoAgA_3dE5ArrayIdLi2E1C7mutable7alignedE'
 Percent: 0.3%
 Total 0.0004s
 Top timings:
   0.0002s ( 45.4%) Early CSE #14
   0.0001s ( 28.4%) SROA #6
   0.0000s ( 11.4%) Simplify the CFG #20
   0.0000s (  4.2%) Prune NRT refops #15
   0.0000s (  2.6%) Lower 'expect' Intrinsics #13
== #1 Module passes (cheap optimization for refprune)
 Percent: 4.7%
 Total 0.0064s
 Top timings:
   0.0037s ( 57.9%) Combine redundant instructions
   0.0007s ( 11.3%) Jump Threading
   0.0006s (  9.4%) Function Integration/Inlining
   0.0002s (  2.5%) Post-Dominator Tree Construction #2
   0.0001s (  2.0%) Prune NRT refops #2
== #2 Module passes (full optimization)
 Percent: 39.

In [8]:
f.signatures

[]

In [11]:
out = pytensor.function([x], y, mode="NUMBA")
out([[1, 2, 3]])

# md = out.vm.jit_fn.get_metadata(out.vm.jit_fn.signatures[0])
# print(md['llvm_pass_timings'])

array([[1.],
       [2.],
       [3.]])

In [12]:
_DIMSHUFFLE_FNS

[CPUDispatcher(<function numba_funcify_DimShuffle.<locals>.transpose at 0x7f76ff442160>),
 CPUDispatcher(<function numba_funcify_DimShuffle.<locals>.transpose at 0x7f76fe7b7740>)]

In [19]:
f = _DIMSHUFFLE_FNS[-1]
md = f.get_metadata(f.signatures[0])
print(md["llvm_pass_timings"])

TypeError: 'NoneType' object is not subscriptable

In [17]:
_DIMSHUFFLE_FNS

CPUDispatcher(<function numba_funcify_DimShuffle.<locals>.transpose at 0x7f76ff442160>)